### ISSUE TITLE
Add safety disclaimer

### ISSUE THREAD

**Issue by Izaic** [patrickjane/ut-plants#5]
I haven't used the app yet, so I am not positive if such a disclaimer exists already, but it would be a really good feature to have a disclaimer show at the top or something that warns the user that the results cannot be guaranteed to be fully accurate, and that the user should still use other means to identify the plant to ensure safety being eating or using it.

Here's a video talking about the issue from AtomicShrimp: https://www.youtube.com/watch?v=sjS0PgC9KSc

**Comment by Danfro** [comment]
The app does only provide the name and images of the plant, no description or information if it is edible. So this disclaimer is not needed in my opinion.

**Comment by patrickjane** [comment]
Regarding missing description: The app displays what is available through the Pl@ntNet API, which does not include a description. So basically I am displaying everything what I can get already.

Regarding disclaimer: It might be worth adding it, and is also pretty trivial, and I think it could make sense. In the end, it wont hurt, so I'm just gonna add it.

**Comment by Danfro** [comment]
Regarding description: I only wanted to state that there is no description and therefore no one is given information about usage or eating a plant. But thanks for confirming, that the API (sadly) does not provide a description.

If you add a disclaimer, maybe make it less intrusive because the risk is not high.

For a disclaimer or warning, I would find it useful to know if my plant-images are uploaded to the servers/website or if they stay on my device. Just so users make sure not to have people in the background of the plants or so.

**Comment by patrickjane** [comment]
Done with [27fd8df](https://github.com/patrickjane/ut-plants/commit/27fd8df9be50243e48972257cb742bc477184546)
